name: Convert Resume to PDF and HTML

on:
  push:
    branches:
      - "**"  # Trigger on all branch pushes

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create output directory and use pandoc
        run: mkdir output
        
      - name: pandoc generate pdf
        uses: docker://pandoc/latex:2.9 
        with:
          args: --output=output/result.pdf
        
      - name: pandoc generate html
        uses: docker://pandoc/latex:2.9 
        with:
          args: --output=output/result.html

      - name: Convert Markdown to PDF
        run: |
          pandoc -s resume.md -o output/resume.pdf --pdf-engine=xelatex
        working-directory: ${{ github.workspace }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: output/resume.pdf

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume-html
          path: output/resume.html
