name: Convert Resume to PDF and HTML

on:
  push:
    branches:
      - "**" # Trigger on all branch pushes

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Create output directory and use pandoc
        run: |
          mkdir output
          cp style.css output/

      - name: pandoc generate html
        uses: docker://pandoc/latex
        with:
          args: >-
            --standalone
            --output=output/resume.html
            --css=style.css
            resume.md

      - name: pandoc generate pdf
        uses: docker://surnet/alpine-wkhtmltopdf:3.20.0-0.12.6-full
        with:
          args: >-
            output/resume.html 
            output/resume.pdf

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: resume
          path: output
